export const PREV_MONTH = 'PREV_MONTH'
export const NEXT_MONTH = 'NEXT_MONTH'
export const NEXT_YEAR = 'NEXT_YEAR'
export const PREV_YEAR = 'PREV_YEAR'
export const SELECT_YEAR_AND_MONTH = 'SELECT_YEAR_AND_MONTH'
export const SELECT_ACTIVE_DATE = 'SELECT_ACTIVE_DATE'

export const CHANGE_CHECKED = 'CHANGE_CHECKED'
export const BIND_DATA = 'BIND_DATA'